import { ScenarioIR, Scenario } from "./ir.ts";

function renderScenario(s: Scenario): string {
  const lines: string[] = [];
  lines.push(`Scenario: ${s.name}`);
  lines.push("");

  if (s.given.length > 0) {
    lines.push("  Given " + s.given[0].text);
    for (let i = 1; i < s.given.length; i++) {
      lines.push("    And " + s.given[i].text);
    }
  }

  if (s.when.length > 0) {
    lines.push("  When " + s.when[0].text);
    for (let i = 1; i < s.when.length; i++) {
      lines.push("    And " + s.when[i].text);
    }
  }

  if (s.then.length > 0) {
    lines.push("  Then " + s.then[0].text);
    for (let i = 1; i < s.then.length; i++) {
      lines.push("    And " + s.then[i].text);
    }
  }

  return lines.join("\n");
}

export function renderGherkin(ir: ScenarioIR, modelName?: string): string {
  const featureName = modelName ?? "Domain Workflow";
  const header = `# Generated by SEMIR Scenario Projection
# Semantic IDs are traceable to the source model.
# Do not edit manually; regenerate from the semantic model.

Feature: ${featureName}
  As a system operator
  I want semantics to be consistent
  So that the system behaves predictably

`;

  const scenarios = ir.scenarios.map(renderScenario).join("\n\n");
  return header + scenarios + "\n";
}
