---- MODULE Reservation ----
\* Generated by SEMIR Formal Verification Projection
\* Semantic IDs are traceable to the source model.
\* Do not edit manually; regenerate from the semantic model.

EXTENDS Naturals, FiniteSets, TLC

VARIABLE reservationState, clock

StateType == {
  Paid, \* semantic: sem://reservation/state/paid
  Expired, \* semantic: sem://reservation/state/expired
  Active, \* semantic: sem://reservation/state/active
}

\* Actions derived from SEMIR assertion graph

PayReservation ==
  /\ reservationState \in {Active}
  /\ reservationState' \in {Paid}
  /\ clock' = clock + 1
  \* semantic: sem://reservation/action/pay-reservation

ExpireReservation ==
  /\ reservationState \in {Active}
  /\ reservationState' \in {Expired}
  /\ clock' = clock + 1
  \* semantic: sem://reservation/action/expire-reservation

CreateReservation ==
  /\ reservationState \in {StateType}
  /\ reservationState' \in {Active}
  /\ clock' = clock + 1
  \* semantic: sem://reservation/action/create-reservation

\* Properties derived from SEMIR invariants

PaidExpiredForbids ==
  [](Paid => ~Expired)
  \* semantic: sem://reservation/assertion/paid-reservations-do-not-expire

PaidExpiredForbids ==
  [](Paid => ~Expired)
  \* semantic: sem://reservation/assertion/expire-forbidden-when-paid

\* Temporal constraints derived from SEMIR assertions

ObservedWithin5s ==
  \* Temporal constraint: observable within 5s
  \* semantic: sem://reservation/assertion/expiry-visibility-within-5s

Init ==
  reservationState \in {Paid, Expired, Active}
  /\ clock = 0

Next ==
  PayReservation
  \/
  ExpireReservation
  \/
  CreateReservation

Spec == Init /\ [][Next]_<<reservationState, clock>>

PROPERTY PaidExpiredForbids
     ∧ PaidExpiredForbids
====