# Generated by SEMIR Scenario Projection
# Semantic IDs are traceable to the source model.
# Do not edit manually; regenerate from the semantic model.

Feature: Domain Workflow
  As a system operator
  I want semantics to be consistent
  So that the system behaves predictably

Scenario: PayReservation lifecycle

  Given the system is in Active state
  When PayReservation is executed
  Then PaymentAccepted occurs
    And the system transitions to Paid state

Scenario: ExpireReservation lifecycle

  Given the system is in Active state
  When ExpireReservation is executed
  Then ReservationExpired occurs
    And the system transitions to Expired state

Scenario: CreateReservation lifecycle

  When CreateReservation is executed
  Then ReservationCreated occurs
    And the system transitions to Active state

Scenario: Paid does not lead to Expired

  Given the system is in Paid state
  When a transition is attempted
  Then the system does NOT transition to Expired

Scenario: ExpireReservation does not lead to Expired

  Given the system is in ExpireReservation state
  When a transition is attempted
  Then the system does NOT transition to Expired
