import { FormalIR } from "./ir";

export function renderTLA(ir: FormalIR): string {
  const lines: string[] = [];

  lines.push(`---- MODULE ${ir.module} ----`);
  lines.push(`\\* Generated by SEMIR Formal Verification Projection`);
  lines.push(`\\* Semantic IDs are traceable to the source model.`);
  lines.push(`\\* Do not edit manually; regenerate from the semantic model.`);
  lines.push("");
  lines.push("EXTENDS Naturals, FiniteSets, TLC");
  lines.push("");

  if (ir.states.length > 0) {
    lines.push("VARIABLE reservationState");
    lines.push("");
    lines.push("StateType == {");
    for (const s of ir.states) {
      lines.push(`  ${s.name}, \\* semantic: ${s.semanticId}`);
    }
    lines.push("}");
    lines.push("");
  }

  if (ir.actions.length > 0) {
    lines.push("\\* Actions derived from SEMIR assertion graph");
    lines.push("");
    for (const action of ir.actions) {
      const fromStates = action.fromStates.length > 0 ? action.fromStates.join(" \\cup ") : "StateType";
      lines.push(`${action.name} ==`);
      lines.push(`  /\\ reservationState \\in {${fromStates}}`);
      if (action.toStates.length > 0) {
        lines.push(`  /\\ reservationState' \\in {${action.toStates.join(", ")}}`);
      }
      lines.push(`  \\* semantic: ${action.semanticId}`);
      lines.push("");
    }
  }

  if (ir.properties.length > 0) {
    lines.push("\\* Properties derived from SEMIR invariants");
    lines.push("");
    for (const prop of ir.properties) {
      lines.push(`${prop.name} ==`);
      lines.push(`  ${prop.formula}`);
      lines.push(`  \\* semantic: ${prop.semanticId}`);
      lines.push("");
    }
  }

  if (ir.constraints.length > 0) {
    lines.push("\\* Constraints derived from SEMIR temporal assertions");
    lines.push("");
    for (const c of ir.constraints) {
      lines.push(`${c.name} ==`);
      lines.push(`  ${c.formula}`);
      lines.push(`  \\* semantic: ${c.semanticId}`);
      lines.push("");
    }
  }

  if (ir.actions.length > 0) {
    lines.push("Init ==");
    lines.push(`  reservationState \\in {${ir.states.map((s) => s.name).join(", ")}}`);
    lines.push("");
    lines.push("Next ==");
    lines.push(
      ir.actions.map((a) => `  ${a.name}`).join("\n  \\/\n")
    );
    lines.push("");
  }

  if (ir.properties.length > 0) {
    lines.push("Spec == Init /\\ [][Next]_reservationState");
    lines.push("");
    lines.push("PROPERTY " + ir.properties.map((p) => p.name).join("\n     ∧ "));
  }

  lines.push("====");

  return lines.join("\n");
}
